version: '3.8'

services:
  nginx:
      build: ./nginx
      volumes:
        - static_volume:/home/app/web/project/static
      ports:
        - 8080:80

  apache:
    build: ./apache
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 8081:80

volumes:
  static_volume:

