CREATE TABLE PEOPLE (
    ID SERIAL,
    NAME VARCHAR UNIQUE NOT NULL,
    GENDER VARCHAR   NOT NULL,
    HOMEWORLD VARCHAR   NOT NULL,
    CONSTRAINT "pk_PEOPLE" PRIMARY KEY (ID)
);

CREATE TABLE STARSHIPS (
    ID SERIAL,
    NAME VARCHAR   NOT NULL,
    MODEL VARCHAR   NOT NULL,
    MANUFACTURER VARCHAR   NOT NULL,
    LADING BIGINT   NOT NULL,
    PILOT VARCHAR NOT NULL,
    CONSTRAINT "pk_STARSHIPS" PRIMARY KEY (ID)
);

ALTER TABLE STARSHIPS ADD CONSTRAINT "fk_STARSHIPS_PEOPLE" FOREIGN KEY(PILOT)
REFERENCES PEOPLE (NAME);

INSERT INTO PEOPLE (NAME, GENDER, HOMEWORLD) VALUES ('n/a', 'n/a', 'n/a');
